syntax on
set smartindent

set autoindent
set confirm
set tabstop=4
set softtabstop=4
set shiftwidth=4
set number
set history=50
set hlsearch
set incsearch
set gdefault
set encoding=utf-8
set fileencodings=utf-8,ucs-bom,shift-jis,gb18030,gbk,gb2312,cp936,utf-16,big5,euc-jp,latin1
colorscheme torte
set guifont=Menlo:h16:cANSI
set langmenu=zn_CN.UTF-8
set helplang=cn
set cmdheight=2
set ruler
set laststatus=2
set showcmd
set scrolloff=3
set showmatch
set matchtime=5
set autowrite
set wildmenu
set linespace=2

